local vim = vim
local bufnr = vim.api.nvim_get_current_buf()
-- vim.keymap.set(
--   "n",
--   "<leader>a",
--   function()
--     vim.cmd.RustLsp('codeAction') -- supports rust-analyzer's grouping
--     -- or vim.lsp.buf.codeAction() if you don't want grouping.
--   end,
--   { silent = true, buffer = bufnr }
-- )
-- vim.keymap.set(
--   "n",
--   "K",  -- Override Neovim's built-in hover keymap with rustaceanvim's hover actions
--   function()
--     vim.cmd.RustLsp({'hover', 'actions'})
--   end,
--   { silent = true, buffer = bufnr }
-- )
--
--
--

-- local rt = require("rust-tools")
-- 
-- rt.setup({
--     server = {
--         on_attach = function(_, bufnr)
--       -- Hover actions
--       vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
--       -- Code action groups
--       vim.keymap.set("n", "<Leader>c", rt.code_action_group.code_action_group, { buffer = bufnr })
--     end,
--     },
-- })
