#!/usr/bin/env bash

# This is just a way to make my life harder... like, I'm really good getting distracted
hyprscratch "$(openssl rand -base64 12)" /home/cbr4l0k/myapps/scripts/whatsapp special wa ephemeral
